services:
    os01:
        image: opensearchproject/opensearch:$OS_VERSION
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
            memlock:
                soft: -1
                hard: -1
        container_name: $OS_NODE1
        environment:
            - node.name=$OS_NODE1
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms$OS_JAVA_MEM -Xmx$OS_JAVA_MEM"
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true

            - discovery.type=single-node
        volumes:
            - os01_data:/usr/share/opensearch/data
        networks:
            - arkime-os

    arkime:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - $OS_NODE1
        environment:
            - OS_HOST=$OS_NODE1
            - OS_PORT=9200
            - CAPTURE=on
            - ARKIME_INTERFACE=eth0
        ports:
            - $ARKIME_PORT:8005
        volumes:
            - arkime_config:/data/config
            - arkime_logs:/data/logs
            - type: bind
              source: $PCAP_DIR
              target: /data/pcap
        networks:
            - arkime-os
    
    suricata:
      image: quay.io/jasonish/suricata:latest
      volumes:
        - ./suri_logs:/var/log/suricata
        - ./suri_etc:/etc/suricata
      cap_add:
        - sys_nice
        - net_raw
        - net_admin
      tty: true
      stdin_open: true
      command: '-i ens18'
      network_mode: host


volumes:
    arkime_config:
    arkime_logs:

    os01_data:


networks:
    arkime-os:
